" set default 'runtimepath' (without ~/.vim folders)
let &runtimepath = printf('%s/vimfiles,%s,%s/vimfiles/after', $VIM, $VIMRUNTIME, $VIM)

" what is the name of the directory containing this file?
let s:portable = expand('<sfile>:p:h')

" add the directory to 'runtimepath'
let &runtimepath = printf('%s,%s,%s/after', s:portable, &runtimepath, s:portable)


set nocompatible
filetype off 

set term=xterm-256color

set rtp+=~/etc/vim/vundle
call vundle#rc()

Bundle 'gmarik/vundle'

filetype plugin indent on 
